groups:
- name: ledgerx
  rules:
  - alert: LedgerxTargetDown
    expr: up{job="ledgerx"} == 0
    for: 1m
    labels: {severity: critical}
    annotations: {summary: "A ledgerx target is down"}
  - alert: HighHttpErrorRate
    expr: (sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) /
           sum(rate(http_server_requests_seconds_count[5m]))) > 0.05
    for: 5m
    labels: {severity: warning}
    annotations: {summary: "HTTP 5xx rate > 5% for 5m"}