server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/ledgerx}
    username: ${SPRING_DATASOURCE_USERNAME:ledgerx}
    password: ${SPRING_DATASOURCE_PASSWORD:ledgerx}
  flyway:
    enabled: true
    table: flyway_history_command
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:host.docker.internal:9092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        linger.ms: 5
        batch.size: 32768
    admin:
      auto-create: false
      fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        ledgerx.outbox.publish.latency: true
        ledgerx.projection.account.latency: true

logging:
  level:
    org.springframework.kafka: INFO
    com.ledgerx.command: INFO