server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ledgerx
    username: ledgerx
    password: ledgerx
  flyway:
    enabled: true
    table: flyway_history_query
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ledgerx-projections-replay
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: batch
    properties:
      max.poll.records: 500

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,mappings
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: never
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        ledgerx.outbox.publish.latency: true
        ledgerx.projection.account.latency: true

logging:
  level:
    org.springframework.kafka: INFO
    com.ledgerx.query: INFO